//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLS_Mobile.Resources.i18n {
    using System;
    
    
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MLSResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MLSResource() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLS_Mobile.Resources.i18n.MLSResource", typeof(MLSResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Absolute humidity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AbsoluteHumidity {
            get {
                return ResourceManager.GetString("AbsoluteHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Atmospheric pressure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AtmosphericPressure {
            get {
                return ResourceManager.GetString("AtmosphericPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clothing coordinator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC_Title {
            get {
                return ResourceManager.GetString("CC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CV = に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_CorrectionValue {
            get {
                return ResourceManager.GetString("CF_CorrectionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to set correction factors. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_FailSetting {
            get {
                return ResourceManager.GetString("CF_FailSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Correction factor {0} of {1} is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Invalid {
            get {
                return ResourceManager.GetString("CF_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * meas. +  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Measurement {
            get {
                return ResourceManager.GetString("CF_Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading correction factors... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Setting {
            get {
                return ResourceManager.GetString("CF_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Correction factor setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Title {
            get {
                return ResourceManager.GetString("CF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clothing unit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClothingUnit {
            get {
                return ResourceManager.GetString("ClothingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CO2 Level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CO2level {
            get {
                return ResourceManager.GetString("CO2level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CR_Connecting {
            get {
                return ResourceManager.GetString("CR_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End measurement? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_FinishAlert {
            get {
                return ResourceManager.GetString("DR_FinishAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start logging... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_StartLogging {
            get {
                return ResourceManager.GetString("DR_StartLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date receiver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_Title {
            get {
                return ResourceManager.GetString("DR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temp. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DrybulbTemperature {
            get {
                return ResourceManager.GetString("DrybulbTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calibrate CO2 Sensor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_CalibrateCO2Sensor {
            get {
                return ResourceManager.GetString("DS_CalibrateCO2Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize CO2 Sensor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_InitializeCO2Sensor {
            get {
                return ResourceManager.GetString("DS_InitializeCO2Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_InvalidNumber {
            get {
                return ResourceManager.GetString("DS_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_LoadSetting {
            get {
                return ResourceManager.GetString("DS_LoadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_OtherSetting {
            get {
                return ResourceManager.GetString("DS_OtherSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SaveSetting {
            get {
                return ResourceManager.GetString("DS_SaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Correction Coefficients に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SetCorrectionCoefficients {
            get {
                return ResourceManager.GetString("DS_SetCorrectionCoefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set M-Logger name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SetName {
            get {
                return ResourceManager.GetString("DS_SetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XBee name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SpecLocalName {
            get {
                return ResourceManager.GetString("DS_SpecLocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SpecName {
            get {
                return ResourceManager.GetString("DS_SpecName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M-Logger version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SpecVersion {
            get {
                return ResourceManager.GetString("DS_SpecVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XBee address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SpecXBAdd {
            get {
                return ResourceManager.GetString("DS_SpecXBAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting date and time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_StartDTime {
            get {
                return ResourceManager.GetString("DS_StartDTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start logging to: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_StartLogging {
            get {
                return ResourceManager.GetString("DS_StartLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target and time interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_TargetAndTimeInterval {
            get {
                return ResourceManager.GetString("DS_TargetAndTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature and relative humidity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_TemperatureAndHumidity {
            get {
                return ResourceManager.GetString("DS_TemperatureAndHumidity", resourceCulture);
            }
        }

        /// <summary>
        ///   Temp / humidity / globe / CO2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_GeneralMeasurement {
            get {
                return ResourceManager.GetString("DS_GeneralMeasurement", resourceCulture);
            }
        }

        internal static string DS_BatteryInfo {
            get { return ResourceManager.GetString("DS_BatteryInfo", resourceCulture); }
        }
        internal static string DS_BatteryVoltage {
            get { return ResourceManager.GetString("DS_BatteryVoltage", resourceCulture); }
        }
        internal static string DS_BatteryType {
            get { return ResourceManager.GetString("DS_BatteryType", resourceCulture); }
        }
        internal static string DS_BatteryTypeAlkaline {
            get { return ResourceManager.GetString("DS_BatteryTypeAlkaline", resourceCulture); }
        }
        internal static string DS_BatteryTypeNiMH {
            get { return ResourceManager.GetString("DS_BatteryTypeNiMH", resourceCulture); }
        }
        internal static string DS_BatteryTypeUnknown {
            get { return ResourceManager.GetString("DS_BatteryTypeUnknown", resourceCulture); }
        }
        internal static string DS_EstimatedRuntime {
            get { return ResourceManager.GetString("DS_EstimatedRuntime", resourceCulture); }
        }
        internal static string DS_RuntimeDays {
            get { return ResourceManager.GetString("DS_RuntimeDays", resourceCulture); }
        }
        internal static string DS_RuntimeHours {
            get { return ResourceManager.GetString("DS_RuntimeHours", resourceCulture); }
        }
        internal static string DS_RuntimeLong {
            get { return ResourceManager.GetString("DS_RuntimeLong", resourceCulture); }
        }
        internal static string DS_LowBatteryWarning {
            get { return ResourceManager.GetString("DS_LowBatteryWarning", resourceCulture); }
        }

        /// <summary>
        ///   Measurement settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_Title {
            get {
                return ResourceManager.GetString("DS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specific enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Enthalpy {
            get {
                return ResourceManager.GetString("Enthalpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Globe temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GlobeTemperature {
            get {
                return ResourceManager.GetString("GlobeTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Globe temperature voltage (deprecated item) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GlobeTemperatureVoltage {
            get {
                return ResourceManager.GetString("GlobeTemperatureVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Illuminance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Illuminance {
            get {
                return ResourceManager.GetString("Illuminance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_Delete {
            get {
                return ResourceManager.GetString("LD_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_DeleteAlert {
            get {
                return ResourceManager.GetString("LD_DeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The maximum number of items displayed has been exceeded. Please copy them on the clipboard. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_Exceed {
            get {
                return ResourceManager.GetString("LD_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Formatting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_Formatting {
            get {
                return ResourceManager.GetString("LD_Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Measured data files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_List {
            get {
                return ResourceManager.GetString("LD_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No data stored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_NoData {
            get {
                return ResourceManager.GetString("LD_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Large data; exporting to shared folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_SaveFileAlert {
            get {
                return ResourceManager.GetString("LD_SaveFileAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_Share {
            get {
                return ResourceManager.GetString("LD_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logging data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_Title {
            get {
                return ResourceManager.GetString("LD_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View activity log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_ViewLog {
            get {
                return ResourceManager.GetString("LD_ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute humidity and Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_AhmdAndDens {
            get {
                return ResourceManager.GetString("MA_AhmdAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute humidity and Enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_AhmdAndEnth {
            get {
                return ResourceManager.GetString("MA_AhmdAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute humdity and Wet-bulb temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_AhmdAndWbt {
            get {
                return ResourceManager.GetString("MA_AhmdAndWbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Absolute humdity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndAhmd {
            get {
                return ResourceManager.GetString("MA_DbtAndAhmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndDens {
            get {
                return ResourceManager.GetString("MA_DbtAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndEnth {
            get {
                return ResourceManager.GetString("MA_DbtAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Relative humidity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndRhmd {
            get {
                return ResourceManager.GetString("MA_DbtAndRhmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Wet-bulb temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndWbt {
            get {
                return ResourceManager.GetString("MA_DbtAndWbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity and Absolute humdity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_RhmdAndAhmd {
            get {
                return ResourceManager.GetString("MA_RhmdAndAhmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity and Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_RhmdAndDens {
            get {
                return ResourceManager.GetString("MA_RhmdAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity and Enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_RhmdAndEnth {
            get {
                return ResourceManager.GetString("MA_RhmdAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity and Wet-bulb temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_RhmdAndWbt {
            get {
                return ResourceManager.GetString("MA_RhmdAndWbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summer-indoor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_SummerIndoor {
            get {
                return ResourceManager.GetString("MA_SummerIndoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summer-outdoor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_SummerOutdoor {
            get {
                return ResourceManager.GetString("MA_SummerOutdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wet-bulb temperature and Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_WbtAndDens {
            get {
                return ResourceManager.GetString("MA_WbtAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Winter-indoor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_WinterIndoor {
            get {
                return ResourceManager.GetString("MA_WinterIndoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Winter-outdoor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_WinterOutdoor {
            get {
                return ResourceManager.GetString("MA_WinterOutdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mean radiant temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MeanRadiantTemperature {
            get {
                return ResourceManager.GetString("MeanRadiantTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metabolic rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetabolicUnit {
            get {
                return ResourceManager.GetString("MetabolicUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moist air calculator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS_Title {
            get {
                return ResourceManager.GetString("MS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative air velocity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RelativeAirVelocity {
            get {
                return ResourceManager.GetString("RelativeAirVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RelativeHumidity {
            get {
                return ResourceManager.GetString("RelativeHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enable Bluetooth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Bluetooth {
            get {
                return ResourceManager.GetString("SC_Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting to M-Logger... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Connecting {
            get {
                return ResourceManager.GetString("SC_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The device cannnot be found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Empty {
            get {
                return ResourceManager.GetString("SC_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enable NearByDevice permission に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_NearByDevice {
            get {
                return ResourceManager.GetString("SC_NearByDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ML scanner に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Title {
            get {
                return ResourceManager.GetString("SC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thermal comfort calculator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TC_Title {
            get {
                return ResourceManager.GetString("TC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Velocity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Velocity voltage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VelocityVoltage {
            get {
                return ResourceManager.GetString("VelocityVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wet-bulb temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WetbulbTemperature {
            get {
                return ResourceManager.GetString("WetbulbTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Permanent Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_PermanentConfirmTitle {
            get {
                return ResourceManager.GetString("DS_PermanentConfirmTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   常設モード確認ダイアログのメッセージ本文 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_PermanentConfirmMessage {
            get {
                return ResourceManager.GetString("DS_PermanentConfirmMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LV_Title {
            get {
                return ResourceManager.GetString("LV_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Clear log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LV_ClearLog {
            get {
                return ResourceManager.GetString("LV_ClearLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Delete all log entries? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LV_ClearConfirmMessage {
            get {
                return ResourceManager.GetString("LV_ClearConfirmMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   No log data available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LV_NoDataAvailable {
            get {
                return ResourceManager.GetString("LV_NoDataAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   M-Logger log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LV_ShareTitle {
            get {
                return ResourceManager.GetString("LV_ShareTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_AlertTitle {
            get {
                return ResourceManager.GetString("ERR_AlertTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Technical details can be reviewed on the Log screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_DetailsInLog {
            get {
                return ResourceManager.GetString("ERR_DetailsInLog", resourceCulture);
            }
        }

        /// <summary>
        ///   接続失敗時のユーザー向けメッセージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_ConnectionFailed {
            get {
                return ResourceManager.GetString("ERR_ConnectionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   機種判別失敗時のユーザー向けメッセージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_ProtocolDetectionFailed {
            get {
                return ResourceManager.GetString("ERR_ProtocolDetectionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to start logging. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_StartLoggingFailed {
            get {
                return ResourceManager.GetString("ERR_StartLoggingFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to save settings to the device. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_SaveSettingsFailed {
            get {
                return ResourceManager.GetString("ERR_SaveSettingsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to load settings from the device. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_LoadSettingsFailed {
            get {
                return ResourceManager.GetString("ERR_LoadSettingsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to update the device name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_SetNameFailed {
            get {
                return ResourceManager.GetString("ERR_SetNameFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to load correction factors. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_LoadCorrectionFailed {
            get {
                return ResourceManager.GetString("ERR_LoadCorrectionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to start CO2 calibration. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_StartCo2CalibrationFailed {
            get {
                return ResourceManager.GetString("ERR_StartCo2CalibrationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Waiting for the first measurement... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_WaitingForFirstSample {
            get {
                return ResourceManager.GetString("DR_WaitingForFirstSample", resourceCulture);
            }
        }

        /// <summary>
        ///   Live (no device connected) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LIVE_NoDevice {
            get {
                return ResourceManager.GetString("LIVE_NoDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Saving correction factors... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_SavingFactors {
            get {
                return ResourceManager.GetString("CF_SavingFactors", resourceCulture);
            }
        }

        /// <summary>
        ///   Starting CO2 calibration... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_StartingCo2Calibration {
            get {
                return ResourceManager.GetString("DS_StartingCo2Calibration", resourceCulture);
            }
        }

        /// <summary>
        ///   Reference CO2 level [ppm] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_PromptCo2RefLevel {
            get {
                return ResourceManager.GetString("DS_PromptCo2RefLevel", resourceCulture);
            }
        }
    }
}
