//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLS_Mobile.Resources.i18n {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TCResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TCResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLS_Mobile.Resources.i18n.TCResource", typeof(TCResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Aircraft, combat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Aircraft_Combat {
            get {
                return ResourceManager.GetString("Act_Aircraft_Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aircraft, instrument landing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Aircraft_InstrumentLanding {
            get {
                return ResourceManager.GetString("Act_Aircraft_InstrumentLanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aircraft, routine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Aircraft_Routine {
            get {
                return ResourceManager.GetString("Act_Aircraft_Routine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automobile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Automobile {
            get {
                return ResourceManager.GetString("Act_Automobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basketball に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Basketball {
            get {
                return ResourceManager.GetString("Act_Basketball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calisthenics/exercise に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Calisthenics {
            get {
                return ResourceManager.GetString("Act_Calisthenics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cooking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Cooking {
            get {
                return ResourceManager.GetString("Act_Cooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dancing, social に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Dancing {
            get {
                return ResourceManager.GetString("Act_Dancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filing, seated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_FilingSeated {
            get {
                return ResourceManager.GetString("Act_FilingSeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filing, standing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_FilingStanding {
            get {
                return ResourceManager.GetString("Act_FilingStanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Handling 50 kg (100 lb) bags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_HandlingBags {
            get {
                return ResourceManager.GetString("Act_HandlingBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Heavy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Heavy {
            get {
                return ResourceManager.GetString("Act_Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seated, heavy limb movement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_HeavyLimbMovement {
            get {
                return ResourceManager.GetString("Act_HeavyLimbMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Heavy vehicle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_HeavyVehicle {
            get {
                return ResourceManager.GetString("Act_HeavyVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   House cleaning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_HouseCleaning {
            get {
                return ResourceManager.GetString("Act_HouseCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lifting/packing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Lifting_Packing {
            get {
                return ResourceManager.GetString("Act_Lifting_Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light (electrical industry) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Light {
            get {
                return ResourceManager.GetString("Act_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seated, reading, or writing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Of_Seated {
            get {
                return ResourceManager.GetString("Act_Of_Seated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pick and shovel work に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_PickAndShovelWork {
            get {
                return ResourceManager.GetString("Act_PickAndShovelWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reclining に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Reclining {
            get {
                return ResourceManager.GetString("Act_Reclining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sawing (table saw) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Sawing {
            get {
                return ResourceManager.GetString("Act_Sawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seated, quiet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Seated_quiet {
            get {
                return ResourceManager.GetString("Act_Seated_quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sleeping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Sleeping {
            get {
                return ResourceManager.GetString("Act_Sleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standing, relaxed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Standing_relaxed {
            get {
                return ResourceManager.GetString("Act_Standing_relaxed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tennis, single に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Tennis {
            get {
                return ResourceManager.GetString("Act_Tennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Driving/Flying に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Title_Driving {
            get {
                return ResourceManager.GetString("Act_Title_Driving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miscellaneous Leisure Activities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Title_LeisureActivities {
            get {
                return ResourceManager.GetString("Act_Title_LeisureActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machine work に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Title_MachineWork {
            get {
                return ResourceManager.GetString("Act_Title_MachineWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miscellaneous Occupational Activities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Title_OccupationalActivities {
            get {
                return ResourceManager.GetString("Act_Title_OccupationalActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Activities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Title_OfficeActivities {
            get {
                return ResourceManager.GetString("Act_Title_OfficeActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Title_Resting {
            get {
                return ResourceManager.GetString("Act_Title_Resting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Walking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Title_Walking {
            get {
                return ResourceManager.GetString("Act_Title_Walking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Typing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Typing {
            get {
                return ResourceManager.GetString("Act_Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0.9 m/s, 3.2 km/h, 2.0 mph に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Walking_09 {
            get {
                return ResourceManager.GetString("Act_Walking_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1.2 m/s, 4.3 km/h, 2.7 mph に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Walking_12 {
            get {
                return ResourceManager.GetString("Act_Walking_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1.8 m/s, 6.8 km/h, 4.2 mph に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Walking_18 {
            get {
                return ResourceManager.GetString("Act_Walking_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Walking about に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_WalkingAbout {
            get {
                return ResourceManager.GetString("Act_WalkingAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrestling, competitive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Act_Wrestling {
            get {
                return ResourceManager.GetString("Act_Wrestling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basketball に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Basketball {
            get {
                return ResourceManager.GetString("Basketball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ankle-length athletic socks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_AnkleLengthAthleticSocks {
            get {
                return ResourceManager.GetString("Clo_AnkleLengthAthleticSocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boots に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Boots {
            get {
                return ResourceManager.GetString("Clo_Boots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bra に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Bra {
            get {
                return ResourceManager.GetString("Clo_Bra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calf-length socks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_CalfLengthSocks {
            get {
                return ResourceManager.GetString("Clo_CalfLengthSocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coveralls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Coveralls {
            get {
                return ResourceManager.GetString("Clo_Coveralls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double-breasted (thick) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_DoubleBreastedThick {
            get {
                return ResourceManager.GetString("Clo_DoubleBreastedThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double-breasted (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_DoubleBreastedThin {
            get {
                return ResourceManager.GetString("Clo_DoubleBreastedThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full slip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_FullSlip {
            get {
                return ResourceManager.GetString("Clo_FullSlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Half-slip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_HalfSlip {
            get {
                return ResourceManager.GetString("Clo_HalfSlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Knee socks (thick) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_KneeSocks_Thick {
            get {
                return ResourceManager.GetString("Clo_KneeSocks_Thick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long-sleeve dress shirt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_LongSleeveDressShirt {
            get {
                return ResourceManager.GetString("Clo_LongSleeveDressShirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long-sleeve flannel shirt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_LongSleeveFlannel {
            get {
                return ResourceManager.GetString("Clo_LongSleeveFlannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long-sleeve long gown (thick) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_LongSleeveLongGownThick {
            get {
                return ResourceManager.GetString("Clo_LongSleeveLongGownThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long-sleeve long wrap robe (thick) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_LongSleeveLongWrapRobeThick {
            get {
                return ResourceManager.GetString("Clo_LongSleeveLongWrapRobeThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long-sleeve pajamas (thick) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_LongSleevePajamasThick {
            get {
                return ResourceManager.GetString("Clo_LongSleevePajamasThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long-sleeve shirtdress (thick) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_LongSleeveShirtDressThick {
            get {
                return ResourceManager.GetString("Clo_LongSleeveShirtDressThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long-sleeve shirtdress (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_LongSleeveShirtDressThin {
            get {
                return ResourceManager.GetString("Clo_LongSleeveShirtDressThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long-sleeve short wrap robe (thick) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_LongSleeveShortWrapRobeThick {
            get {
                return ResourceManager.GetString("Clo_LongSleeveShortWrapRobeThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long-sleeve sweatshirt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_LongSleeveSweatShirt {
            get {
                return ResourceManager.GetString("Clo_LongSleeveSweatShirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long-sleeve (thick) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_LongSleeveThick {
            get {
                return ResourceManager.GetString("Clo_LongSleeveThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long-sleeve (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_LongSleeveThin {
            get {
                return ResourceManager.GetString("Clo_LongSleeveThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long underwear bottoms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_LongUnderwearBottoms {
            get {
                return ResourceManager.GetString("Clo_LongUnderwearBottoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long underwear top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_LongUnderwearTop {
            get {
                return ResourceManager.GetString("Clo_LongUnderwearTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Men&apos;s briefs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_MensBriefs {
            get {
                return ResourceManager.GetString("Clo_MensBriefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overalls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Overalls {
            get {
                return ResourceManager.GetString("Clo_Overalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Panties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Panties {
            get {
                return ResourceManager.GetString("Clo_Panties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pantyhose/stockings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Pantyhose_Stockings {
            get {
                return ResourceManager.GetString("Clo_Pantyhose_Stockings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sandals/thongs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Sandals_Thongs {
            get {
                return ResourceManager.GetString("Clo_Sandals_Thongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shoes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Shoes {
            get {
                return ResourceManager.GetString("Clo_Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short shorts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_ShortShorts {
            get {
                return ResourceManager.GetString("Clo_ShortShorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short-sleeve dress shirt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_ShortSleeveDressShirt {
            get {
                return ResourceManager.GetString("Clo_ShortSleeveDressShirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short-sleeve hospital gown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_ShortSleeveHospitalGown {
            get {
                return ResourceManager.GetString("Clo_ShortSleeveHospitalGown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short-sleeve knit sport shirt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_ShortSleeveKnit {
            get {
                return ResourceManager.GetString("Clo_ShortSleeveKnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short-sleeve pajamas (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_ShortSleevePajamasThin {
            get {
                return ResourceManager.GetString("Clo_ShortSleevePajamasThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short-sleeve shirtdress (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_ShortSleeveShirtDressThin {
            get {
                return ResourceManager.GetString("Clo_ShortSleeveShirtDressThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short-sleeve short robe (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_ShortSleeveShortRobeThin {
            get {
                return ResourceManager.GetString("Clo_ShortSleeveShortRobeThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single-breasted (thick) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_SingleBreastedThick {
            get {
                return ResourceManager.GetString("Clo_SingleBreastedThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single-breasted (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_SingleBreastedThin {
            get {
                return ResourceManager.GetString("Clo_SingleBreastedThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skirt (thick) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_SkirtThick {
            get {
                return ResourceManager.GetString("Clo_SkirtThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skirt (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_SkirtThin {
            get {
                return ResourceManager.GetString("Clo_SkirtThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sleeveless/scoop-neck blouse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Sleeveless {
            get {
                return ResourceManager.GetString("Clo_Sleeveless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sleeveless long gown (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_SleevelessLongGownThin {
            get {
                return ResourceManager.GetString("Clo_SleevelessLongGownThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sleeveless short gown (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_SleevelessShortGownThin {
            get {
                return ResourceManager.GetString("Clo_SleevelessShortGownThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sleeveless vest (thick) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_SleevelessSweatVestThick {
            get {
                return ResourceManager.GetString("Clo_SleevelessSweatVestThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sleeveless vest (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_SleevelessSweatVestThin {
            get {
                return ResourceManager.GetString("Clo_SleevelessSweatVestThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sleeveless, scoop neck (thick), i.e.,jumper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_SleevelessThick {
            get {
                return ResourceManager.GetString("Clo_SleevelessThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sleeveless, scoop neck (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_SleevelessThin {
            get {
                return ResourceManager.GetString("Clo_SleevelessThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sleeveless vest (thick) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_SleevelessVestThick {
            get {
                return ResourceManager.GetString("Clo_SleevelessVestThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sleeveless vest (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_SleevelessVestThin {
            get {
                return ResourceManager.GetString("Clo_SleevelessVestThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slippers (quilted, pile lined) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Slippers {
            get {
                return ResourceManager.GetString("Clo_Slippers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Straight trousers (thick) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_StraightTrousersThick {
            get {
                return ResourceManager.GetString("Clo_StraightTrousersThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Straight trousers (thin) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_StraightTrousersThin {
            get {
                return ResourceManager.GetString("Clo_StraightTrousersThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sweatpants に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Sweatpants {
            get {
                return ResourceManager.GetString("Clo_Sweatpants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dress and Skirts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Title_DressAndSkirts {
            get {
                return ResourceManager.GetString("Clo_Title_DressAndSkirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Footwear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Title_Footwear {
            get {
                return ResourceManager.GetString("Clo_Title_Footwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shirts and Blouses に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Title_ShirtsAndBlouses {
            get {
                return ResourceManager.GetString("Clo_Title_ShirtsAndBlouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sleepwear and Robes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Title_SleepwearAndRobes {
            get {
                return ResourceManager.GetString("Clo_Title_SleepwearAndRobes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suit Jackets and Vests に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Title_SuitJacketsAndVests {
            get {
                return ResourceManager.GetString("Clo_Title_SuitJacketsAndVests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sweaters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Title_Sweaters {
            get {
                return ResourceManager.GetString("Clo_Title_Sweaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trousers and Coveralls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Title_TrousersAndCoveralls {
            get {
                return ResourceManager.GetString("Clo_Title_TrousersAndCoveralls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underwear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_Title_Underwear {
            get {
                return ResourceManager.GetString("Clo_Title_Underwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T-shirt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_TShirt {
            get {
                return ResourceManager.GetString("Clo_TShirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Walking shorts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clo_WalkingShorts {
            get {
                return ResourceManager.GetString("Clo_WalkingShorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cooking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cooling {
            get {
                return ResourceManager.GetString("Cooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dancing, social に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dancing {
            get {
                return ResourceManager.GetString("Dancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Driving/Flying: Aircraft, routine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Driving_Aircraft1 {
            get {
                return ResourceManager.GetString("Driving_Aircraft1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Driving/Flying: Aircraft, instrument landing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Driving_Aircraft2 {
            get {
                return ResourceManager.GetString("Driving_Aircraft2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Driving/Flying: Aircraft, combat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Driving_Aircraft3 {
            get {
                return ResourceManager.GetString("Driving_Aircraft3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Driving/Flying: Automobile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Driving_Automobile {
            get {
                return ResourceManager.GetString("Driving_Automobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Driving/Flying: Heavy vehicle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Driving_Heavy {
            get {
                return ResourceManager.GetString("Driving_Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name must be one-byte characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_OnebyteAlert {
            get {
                return ResourceManager.GetString("DS_OnebyteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calisthenics/exercise に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seated, heavy limb movement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeavyLimbMovement {
            get {
                return ResourceManager.GetString("HeavyLimbMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   House cleaning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HouseCleaning {
            get {
                return ResourceManager.GetString("HouseCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machine work: Handling 50 kg (100 lb) bags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mw_HandlingBags {
            get {
                return ResourceManager.GetString("Mw_HandlingBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machine work: Heavy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mw_Heavy {
            get {
                return ResourceManager.GetString("Mw_Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machine work: Light (electrical industry) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mw_Light {
            get {
                return ResourceManager.GetString("Mw_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machine work: Sawing (table saw) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mw_Sawing {
            get {
                return ResourceManager.GetString("Mw_Sawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machine work: Pick and shovel work に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mw_ShovelWork {
            get {
                return ResourceManager.GetString("Mw_ShovelWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Activities: Filing, seated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Of_FilingSeated {
            get {
                return ResourceManager.GetString("Of_FilingSeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Activities: Filing, standing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Of_FilingStanding {
            get {
                return ResourceManager.GetString("Of_FilingStanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Activities: Lifting/packing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Of_Lifting {
            get {
                return ResourceManager.GetString("Of_Lifting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Activities: Seated, reading, or writing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Of_Seated {
            get {
                return ResourceManager.GetString("Of_Seated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Activities: Typing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Of_Typing {
            get {
                return ResourceManager.GetString("Of_Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Activities: Walking about に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Of_Walking {
            get {
                return ResourceManager.GetString("Of_Walking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resting: Reclining に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rs_Reclining {
            get {
                return ResourceManager.GetString("Rs_Reclining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resting: Seated, quiet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rs_Seated {
            get {
                return ResourceManager.GetString("Rs_Seated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resting: Sleeping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rs_Sleeping {
            get {
                return ResourceManager.GetString("Rs_Sleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resting: Standing, relaxed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rs_Standing {
            get {
                return ResourceManager.GetString("Rs_Standing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select activity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectActivity {
            get {
                return ResourceManager.GetString("SelectActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select clothes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectClothes {
            get {
                return ResourceManager.GetString("SelectClothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tennis, single に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tennis {
            get {
                return ResourceManager.GetString("Tennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Walking: 0.9 m/s, 3.2 km/h, 2.0 mph に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Walking_09 {
            get {
                return ResourceManager.GetString("Walking_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Walking: 1.2 m/s, 4.3 km/h, 2.7 mph に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Walking_12 {
            get {
                return ResourceManager.GetString("Walking_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Walking: 1.8 m/s, 6.8 km/h, 4.2 mph に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Walking_18 {
            get {
                return ResourceManager.GetString("Walking_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrestling, competitive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Wrestling {
            get {
                return ResourceManager.GetString("Wrestling", resourceCulture);
            }
        }
    }
}
