//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLS_Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MLSResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MLSResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLS_Mobile.Resources.MLSResource", typeof(MLSResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About this software に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutThisSoftware {
            get {
                return ResourceManager.GetString("AboutThisSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute humidity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AbsoluteHumdity {
            get {
                return ResourceManager.GetString("AbsoluteHumdity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Atmospheric pressure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AtmosphericPressure {
            get {
                return ResourceManager.GetString("AtmosphericPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Back {
            get {
                return ResourceManager.GetString("CF_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CV = に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_CorrectionValue {
            get {
                return ResourceManager.GetString("CF_CorrectionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * meas. +  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Measurement {
            get {
                return ResourceManager.GetString("CF_Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Set {
            get {
                return ResourceManager.GetString("CF_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No wind voltage:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_VelocityVoltage {
            get {
                return ResourceManager.GetString("CF_VelocityVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clothing unit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClothingUnit {
            get {
                return ResourceManager.GetString("ClothingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect to MLogger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectMLogger {
            get {
                return ResourceManager.GetString("ConnectMLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to start logging. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_FailStarting {
            get {
                return ResourceManager.GetString("DR_FailStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to stop logging. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_FailStopping {
            get {
                return ResourceManager.GetString("DR_FailStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to finish the measurement? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_FinishAlert {
            get {
                return ResourceManager.GetString("DR_FinishAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finish measurement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_FinishMeasurement {
            get {
                return ResourceManager.GetString("DR_FinishMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start logging... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_StartLogging {
            get {
                return ResourceManager.GetString("DR_StartLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop logging... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_StopLogging {
            get {
                return ResourceManager.GetString("DR_StopLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temp. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DrybulbTemperature {
            get {
                return ResourceManager.GetString("DrybulbTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set correction factor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_CFactor {
            get {
                return ResourceManager.GetString("DS_CFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Communicate with MLogger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_Communicate {
            get {
                return ResourceManager.GetString("DS_Communicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_Info {
            get {
                return ResourceManager.GetString("DS_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_LoadSetting {
            get {
                return ResourceManager.GetString("DS_LoadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Measurement settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_MeasurementSettings {
            get {
                return ResourceManager.GetString("DS_MeasurementSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SaveSetting {
            get {
                return ResourceManager.GetString("DS_SaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MAC address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SpecMACAdd {
            get {
                return ResourceManager.GetString("DS_SpecMACAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SpecName {
            get {
                return ResourceManager.GetString("DS_SpecName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MLogger version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SpecVersion {
            get {
                return ResourceManager.GetString("DS_SpecVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XBee address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SpecXBAdd {
            get {
                return ResourceManager.GetString("DS_SpecXBAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_Start {
            get {
                return ResourceManager.GetString("DS_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting date and time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_StartDTime {
            get {
                return ResourceManager.GetString("DS_StartDTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target and time interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_TargetAndTimeInterval {
            get {
                return ResourceManager.GetString("DS_TargetAndTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature and relative humidity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_TemperatureAndHumidity {
            get {
                return ResourceManager.GetString("DS_TemperatureAndHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit measured data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditMeasuredData {
            get {
                return ResourceManager.GetString("EditMeasuredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specific enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Enthalpy {
            get {
                return ResourceManager.GetString("Enthalpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Globe temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GlobeTemperature {
            get {
                return ResourceManager.GetString("GlobeTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Illuminance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Illuminance {
            get {
                return ResourceManager.GetString("Illuminance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy to CLP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_Copy {
            get {
                return ResourceManager.GetString("LD_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_Delete {
            get {
                return ResourceManager.GetString("LD_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Measured data files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_List {
            get {
                return ResourceManager.GetString("LD_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No data stored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_NoData {
            get {
                return ResourceManager.GetString("LD_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute humidity and Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_AhmdAndDens {
            get {
                return ResourceManager.GetString("MA_AhmdAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute humidity and Enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_AhmdAndEnth {
            get {
                return ResourceManager.GetString("MA_AhmdAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute humdity and Wet-bulb temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_AhmdAndWbt {
            get {
                return ResourceManager.GetString("MA_AhmdAndWbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Absolute humdity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndAhmd {
            get {
                return ResourceManager.GetString("MA_DbtAndAhmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndDens {
            get {
                return ResourceManager.GetString("MA_DbtAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndEnth {
            get {
                return ResourceManager.GetString("MA_DbtAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Relative humidity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndRhmd {
            get {
                return ResourceManager.GetString("MA_DbtAndRhmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Wet-bulb temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndWbt {
            get {
                return ResourceManager.GetString("MA_DbtAndWbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity and Absolute humdity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_RhmdAndAhmd {
            get {
                return ResourceManager.GetString("MA_RhmdAndAhmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity and Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_RhmdAndDens {
            get {
                return ResourceManager.GetString("MA_RhmdAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity and Enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_RhmdAndEnth {
            get {
                return ResourceManager.GetString("MA_RhmdAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity and Wet-bulb temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_RhmdAndWbt {
            get {
                return ResourceManager.GetString("MA_RhmdAndWbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summer condition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_SummerButton {
            get {
                return ResourceManager.GetString("MA_SummerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wet-bulb temperature and Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_WbtAndDens {
            get {
                return ResourceManager.GetString("MA_WbtAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wet-bulb temperature and Enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_WbtAndEnth {
            get {
                return ResourceManager.GetString("MA_WbtAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Winter condition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_WinterButton {
            get {
                return ResourceManager.GetString("MA_WinterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mean radiant temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MeanRadiantTemperature {
            get {
                return ResourceManager.GetString("MeanRadiantTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metabolic rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetabolicUnit {
            get {
                return ResourceManager.GetString("MetabolicUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moist air calculator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MoistAirCalculator {
            get {
                return ResourceManager.GetString("MoistAirCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative air velocity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RelativeAirVelocity {
            get {
                return ResourceManager.GetString("RelativeAirVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RelativeHumidity {
            get {
                return ResourceManager.GetString("RelativeHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enable Bluetooth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Bluetooth {
            get {
                return ResourceManager.GetString("SC_Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting MLogger... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Connecting {
            get {
                return ResourceManager.GetString("SC_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MLogger not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Notfound {
            get {
                return ResourceManager.GetString("SC_Notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scanning MLogger... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Scannning {
            get {
                return ResourceManager.GetString("SC_Scannning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MLogger list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Title {
            get {
                return ResourceManager.GetString("SC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thermal comfort calculator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThermalComfortCalculator {
            get {
                return ResourceManager.GetString("ThermalComfortCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Velocity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wet-bulb temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WetbulbTemperature {
            get {
                return ResourceManager.GetString("WetbulbTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
