//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLS_Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ThermalComfortRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThermalComfortRes() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLS_Mobile.Resources.ThermalComfortRes", typeof(ThermalComfortRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Basketball に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Basketball {
            get {
                return ResourceManager.GetString("Basketball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cooking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cooling {
            get {
                return ResourceManager.GetString("Cooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dancing, social に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dancing {
            get {
                return ResourceManager.GetString("Dancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Driving/Flying: Aircraft, routine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Driving_Aircraft1 {
            get {
                return ResourceManager.GetString("Driving_Aircraft1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Driving/Flying: Aircraft, instrument landing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Driving_Aircraft2 {
            get {
                return ResourceManager.GetString("Driving_Aircraft2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Driving/Flying: Aircraft, combat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Driving_Aircraft3 {
            get {
                return ResourceManager.GetString("Driving_Aircraft3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Driving/Flying: Automobile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Driving_Automobile {
            get {
                return ResourceManager.GetString("Driving_Automobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Driving/Flying: Heavy vehicle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Driving_Heavy {
            get {
                return ResourceManager.GetString("Driving_Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calisthenics/exercise に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seated, heavy limb movement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeavyLimbMovement {
            get {
                return ResourceManager.GetString("HeavyLimbMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   House cleaning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HouseCleaning {
            get {
                return ResourceManager.GetString("HouseCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machine work: Handling 50 kg (100 lb) bags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mw_HandlingBags {
            get {
                return ResourceManager.GetString("Mw_HandlingBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machine work: Heavy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mw_Heavy {
            get {
                return ResourceManager.GetString("Mw_Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machine work: Light (electrical industry) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mw_Light {
            get {
                return ResourceManager.GetString("Mw_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machine work: Sawing (table saw) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mw_Sawing {
            get {
                return ResourceManager.GetString("Mw_Sawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machine work: Pick and shovel work に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mw_ShovelWork {
            get {
                return ResourceManager.GetString("Mw_ShovelWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Activities: Filing, seated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Of_FilingSeated {
            get {
                return ResourceManager.GetString("Of_FilingSeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Activities: Filing, standing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Of_FilingStanding {
            get {
                return ResourceManager.GetString("Of_FilingStanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Activities: Lifting/packing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Of_Lifting {
            get {
                return ResourceManager.GetString("Of_Lifting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Activities: Seated, reading, or writing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Of_Seated {
            get {
                return ResourceManager.GetString("Of_Seated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Activities: Typing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Of_Typing {
            get {
                return ResourceManager.GetString("Of_Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Activities: Walking about に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Of_Walking {
            get {
                return ResourceManager.GetString("Of_Walking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resting: Reclining に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rs_Reclining {
            get {
                return ResourceManager.GetString("Rs_Reclining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resting: Seated, quiet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rs_Seated {
            get {
                return ResourceManager.GetString("Rs_Seated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resting: Sleeping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rs_Sleeping {
            get {
                return ResourceManager.GetString("Rs_Sleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resting: Standing, relaxed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rs_Standing {
            get {
                return ResourceManager.GetString("Rs_Standing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tennis, single に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tennis {
            get {
                return ResourceManager.GetString("Tennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Walking: 0.9 m/s, 3.2 km/h, 2.0 mph に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Walking_09 {
            get {
                return ResourceManager.GetString("Walking_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Walking: 1.2 m/s, 4.3 km/h, 2.7 mph に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Walking_12 {
            get {
                return ResourceManager.GetString("Walking_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Walking: 1.8 m/s, 6.8 km/h, 4.2 mph に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Walking_18 {
            get {
                return ResourceManager.GetString("Walking_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrestling, competitive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Wrestling {
            get {
                return ResourceManager.GetString("Wrestling", resourceCulture);
            }
        }
    }
}
