//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLServer.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLServer.i18n.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base volt.:.
        /// </summary>
        internal static string CFF_Bvoltage {
            get {
                return ResourceManager.GetString("CFF_Bvoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corr. value =.
        /// </summary>
        internal static string CFF_CValue {
            get {
                return ResourceManager.GetString("CFF_CValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Meas. value =.
        /// </summary>
        internal static string CFF_MValue {
            get {
                return ResourceManager.GetString("CFF_MValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction factors.
        /// </summary>
        internal static string CFF_Title {
            get {
                return ResourceManager.GetString("CFF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date time.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBT/RH.
        /// </summary>
        internal static string DBTandRH {
            get {
                return ResourceManager.GetString("DBTandRH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry-bulb temperature.
        /// </summary>
        internal static string DBTemp {
            get {
                return ResourceManager.GetString("DBTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General purpose voltage.
        /// </summary>
        internal static string GeneralPurposeVoltage {
            get {
                return ResourceManager.GetString("GeneralPurposeVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globe temperature.
        /// </summary>
        internal static string GlbTemp {
            get {
                return ResourceManager.GetString("GlbTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illuminance.
        /// </summary>
        internal static string Illuminance {
            get {
                return ResourceManager.GetString("Illuminance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time interval should be set in the range of 1-86400 seconds..
        /// </summary>
        internal static string MF_Alrt_Interval {
            get {
                return ResourceManager.GetString("MF_Alrt_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input of {0} measurement time interval..
        /// </summary>
        internal static string MF_Alrt_InvalidInput {
            get {
                return ResourceManager.GetString("MF_Alrt_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply setting.
        /// </summary>
        internal static string MF_ApplySetting {
            get {
                return ResourceManager.GetString("MF_ApplySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string MF_Connect {
            get {
                return ResourceManager.GetString("MF_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to XBee (coordinator) via COM port.
        /// </summary>
        internal static string MF_Connect_Def {
            get {
                return ResourceManager.GetString("MF_Connect_Def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection succeeded..
        /// </summary>
        internal static string MF_ConnectionSucceeded {
            get {
                return ResourceManager.GetString("MF_ConnectionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to XBee (coordinator) on {0}.
        /// </summary>
        internal static string MF_ConnectPort {
            get {
                return ResourceManager.GetString("MF_ConnectPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string MF_Disconnect {
            get {
                return ResourceManager.GetString("MF_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect the COM port Xbee (coordinator).
        /// </summary>
        internal static string MF_Disconnect_Def {
            get {
                return ResourceManager.GetString("MF_Disconnect_Def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect to XBee (coordinator) on {0}.
        /// </summary>
        internal static string MF_DisconnectPort {
            get {
                return ResourceManager.GetString("MF_DisconnectPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable.
        /// </summary>
        internal static string MF_Editable {
            get {
                return ResourceManager.GetString("MF_Editable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load &apos;cf.ini&apos;..
        /// </summary>
        internal static string MF_ErrCF {
            get {
                return ResourceManager.GetString("MF_ErrCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to {0}..
        /// </summary>
        internal static string MF_FileIsUsing {
            get {
                return ResourceManager.GetString("MF_FileIsUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        internal static string MF_Initializing {
            get {
                return ResourceManager.GetString("MF_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        internal static string MF_MeasureCBX {
            get {
                return ResourceManager.GetString("MF_MeasureCBX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring.
        /// </summary>
        internal static string MF_Measuring {
            get {
                return ResourceManager.GetString("MF_Measuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaurement starting date time.
        /// </summary>
        internal static string MF_MStartDTime {
            get {
                return ResourceManager.GetString("MF_MStartDTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to connect to the following ports: .
        /// </summary>
        internal static string MF_PortChg {
            get {
                return ResourceManager.GetString("MF_PortChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to SD card.
        /// </summary>
        internal static string MF_SaveToSDCard {
            get {
                return ResourceManager.GetString("MF_SaveToSDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string MF_Search {
            get {
                return ResourceManager.GetString("MF_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the MLogger (XBee end-device).
        /// </summary>
        internal static string MF_Search_Def {
            get {
                return ResourceManager.GetString("MF_Search_Def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set correction factors.
        /// </summary>
        internal static string MF_SetCorrectionFactors {
            get {
                return ResourceManager.GetString("MF_SetCorrectionFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start data collecting.
        /// </summary>
        internal static string MF_StartDataCollecting {
            get {
                return ResourceManager.GetString("MF_StartDataCollecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start logging (SD card).
        /// </summary>
        internal static string MF_StartLoggingToSDCard {
            get {
                return ResourceManager.GetString("MF_StartLoggingToSDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start scanning MLogger ....
        /// </summary>
        internal static string MF_StartSearch {
            get {
                return ResourceManager.GetString("MF_StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to connect XBee (coordinator) on {0}.
        /// </summary>
        internal static string MF_TryConnectPort {
            get {
                return ResourceManager.GetString("MF_TryConnectPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximity.
        /// </summary>
        internal static string Proximity {
            get {
                return ResourceManager.GetString("Proximity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiative temperature.
        /// </summary>
        internal static string RadTemp {
            get {
                return ResourceManager.GetString("RadTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative humidity.
        /// </summary>
        internal static string RHumid {
            get {
                return ResourceManager.GetString("RHumid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;ja&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;robots&quot; content=&quot;noindex,nofollow&quot;&gt;
        ///    &lt;meta http-equiv=&quot;refresh&quot; content=&quot;60; URL=&quot;&gt;
        ///    &lt;title&gt;Measurement status&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;style.css&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;h2&gt;Measurement status&lt;/h2&gt;
        ///
        ///    &lt;b&gt;No. of MLoggers connected:&lt;/b&gt;&lt;!--ML_NUMBER--&gt; unit(s)&lt;br&gt;&lt;br&gt;
        ///    &lt;b&gt;List of MLoggers:&lt;/b&gt;&lt;br&gt;
        ///    &lt;div id=&quot;loggers&quot;&gt;
        ///        Filtering &lt;input class=&quot;search&quot;&gt;&lt;br&gt;&lt;br&gt;
        ///        &lt;table align=&quot;left&quot;&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string topPage_html {
            get {
                return ResourceManager.GetString("topPage_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
    }
}
