//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLS_Mobile.Resources.i18n {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DescriptionText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescriptionText() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLS_Mobile.Resources.i18n.DescriptionText", typeof(DescriptionText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   You can configure whether to measure each item, set the measurement time interval, and specify when to start the measurement.
        ///
        ///Wind speed consumes the most power, and the chosen measurement interval significantly impacts the duration for which measurements can continue.
        ///
        ///If the measurement start date and time are set to a past time relative to the current time, the measurement will begin immediately.
        ///
        ///If you make any changes to these settings, you must send the updated configuration to overwrite the interna [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MeasurementInterval {
            get {
                return ResourceManager.GetString("MeasurementInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   These settings are only relevant when the data is transmitted to and stored on a PC.
        ///
        ///Enabling &quot;Permanent Mode&quot; will start the measurement automatically upon startup.
        ///Pressing and holding the reset switch will return the M-Logger to normal mode.
        ///
        ///PAN ID is the Zigbee communication ID, with a default value of 19800614.
        ///
        ///When the communication status LED is enabled, the Zigbee communication status will be indicated by the LED blinking. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PCSetting {
            get {
                return ResourceManager.GetString("PCSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entering text here will append it to the end of each measurement data entry.
        ///This can be useful for adding notes to record when measurement conditions were changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShortMemo {
            get {
                return ResourceManager.GetString("ShortMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options for Storing Measured Data
        ///
        ///Phone:
        ///Store the data internally on this iPhone or Android device.
        ///
        ///PC:
        ///Transmit the data using Zigbee to a PC or Raspberry Pi equipped with an XBee module.
        ///
        ///Flash:
        ///Write the data to a flash memory inserted into the M-Logger. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartLogging {
            get {
                return ResourceManager.GetString("StartLogging", resourceCulture);
            }
        }
    }
}
