//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLS_Mobile.Resources.i18n {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MLSResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MLSResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLS_Mobile.Resources.i18n.MLSResource", typeof(MLSResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About this software に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutThisSoftware {
            get {
                return ResourceManager.GetString("AboutThisSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute humidity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AbsoluteHumidity {
            get {
                return ResourceManager.GetString("AbsoluteHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Atmospheric pressure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AtmosphericPressure {
            get {
                return ResourceManager.GetString("AtmosphericPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clothing coordinator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC_Title {
            get {
                return ResourceManager.GetString("CC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Back {
            get {
                return ResourceManager.GetString("CF_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CV = に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_CorrectionValue {
            get {
                return ResourceManager.GetString("CF_CorrectionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discard the entries ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Discard {
            get {
                return ResourceManager.GetString("CF_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to set correction factors. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_FailSetting {
            get {
                return ResourceManager.GetString("CF_FailSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Correction factor {0} of {1} is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Invalid {
            get {
                return ResourceManager.GetString("CF_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage at 0m/s velocity is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_InvalidVelocity1 {
            get {
                return ResourceManager.GetString("CF_InvalidVelocity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage at 0m/s velocity should be positive. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_InvalidVelocity2 {
            get {
                return ResourceManager.GetString("CF_InvalidVelocity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading correction factors... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Loading {
            get {
                return ResourceManager.GetString("CF_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load correction factors. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_LoadingError {
            get {
                return ResourceManager.GetString("CF_LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * meas. +  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Measurement {
            get {
                return ResourceManager.GetString("CF_Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Set {
            get {
                return ResourceManager.GetString("CF_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading correction factors... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Setting {
            get {
                return ResourceManager.GetString("CF_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Correction factor setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_Title {
            get {
                return ResourceManager.GetString("CF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No wind voltage:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CF_VelocityVoltage {
            get {
                return ResourceManager.GetString("CF_VelocityVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clothing unit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClothingUnit {
            get {
                return ResourceManager.GetString("ClothingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect to M-Logger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectMLogger {
            get {
                return ResourceManager.GetString("ConnectMLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic temperature calibration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CR_AutoCalTemp {
            get {
                return ResourceManager.GetString("CR_AutoCalTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic velocity calibration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CR_AutoCalVel {
            get {
                return ResourceManager.GetString("CR_AutoCalVel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calibrate velocity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CR_CalibrateVelocityVoltage {
            get {
                return ResourceManager.GetString("CR_CalibrateVelocityVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calibrating time: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CR_CalibratingTime {
            get {
                return ResourceManager.GetString("CR_CalibratingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set correction factor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CR_CFactor {
            get {
                return ResourceManager.GetString("CR_CFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CR_Connecting {
            get {
                return ResourceManager.GetString("CR_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CR_ConnectionFailed {
            get {
                return ResourceManager.GetString("CR_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End calibration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CR_EndCalibration {
            get {
                return ResourceManager.GetString("CR_EndCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calibration has started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CR_StartCalibration {
            get {
                return ResourceManager.GetString("CR_StartCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calibrator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CR_Title {
            get {
                return ResourceManager.GetString("CR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to start logging. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_FailStarting {
            get {
                return ResourceManager.GetString("DR_FailStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to stop logging. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_FailStopping {
            get {
                return ResourceManager.GetString("DR_FailStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End measurement? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_FinishAlert {
            get {
                return ResourceManager.GetString("DR_FinishAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finish measurement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_FinishMeasurement {
            get {
                return ResourceManager.GetString("DR_FinishMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start logging... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_StartLogging {
            get {
                return ResourceManager.GetString("DR_StartLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop logging... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_StopLogging {
            get {
                return ResourceManager.GetString("DR_StopLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date receiver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_Title {
            get {
                return ResourceManager.GetString("DR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temp. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DrybulbTemperature {
            get {
                return ResourceManager.GetString("DrybulbTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adjust velocity voltage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_AdjustVelocityVoltage {
            get {
                return ResourceManager.GetString("DS_AdjustVelocityVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calibration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_Calibrate {
            get {
                return ResourceManager.GetString("DS_Calibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change PAN ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_ChangePANID {
            get {
                return ResourceManager.GetString("DS_ChangePANID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start logging to PC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_ConnectToPC {
            get {
                return ResourceManager.GetString("DS_ConnectToPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable status LED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_DisableZigLED {
            get {
                return ResourceManager.GetString("DS_DisableZigLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable status LED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_EnableZigLED {
            get {
                return ResourceManager.GetString("DS_EnableZigLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_InvalidNumber {
            get {
                return ResourceManager.GetString("DS_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading status... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_LoadingZigLED {
            get {
                return ResourceManager.GetString("DS_LoadingZigLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_LoadSetting {
            get {
                return ResourceManager.GetString("DS_LoadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logging to TF/MM card に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_LoggingToMF {
            get {
                return ResourceManager.GetString("DS_LoggingToMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logging to Smartphone に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_LoggingToSmartPhone {
            get {
                return ResourceManager.GetString("DS_LoggingToSmartPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name must be one-byte characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_OnebyteAlert {
            get {
                return ResourceManager.GetString("DS_OnebyteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_OtherSetting {
            get {
                return ResourceManager.GetString("DS_OtherSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SaveSetting {
            get {
                return ResourceManager.GetString("DS_SaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set M-Logger name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SetName {
            get {
                return ResourceManager.GetString("DS_SetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set to permanent mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SetToPermanentMode {
            get {
                return ResourceManager.GetString("DS_SetToPermanentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XBee name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SpecLocalName {
            get {
                return ResourceManager.GetString("DS_SpecLocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MAC address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SpecMACAdd {
            get {
                return ResourceManager.GetString("DS_SpecMACAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SpecName {
            get {
                return ResourceManager.GetString("DS_SpecName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M-Logger version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SpecVersion {
            get {
                return ResourceManager.GetString("DS_SpecVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XBee address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_SpecXBAdd {
            get {
                return ResourceManager.GetString("DS_SpecXBAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting date and time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_StartDTime {
            get {
                return ResourceManager.GetString("DS_StartDTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start logging に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_StartLogging {
            get {
                return ResourceManager.GetString("DS_StartLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target and time interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_TargetAndTimeInterval {
            get {
                return ResourceManager.GetString("DS_TargetAndTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature and relative humidity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_TemperatureAndHumidity {
            get {
                return ResourceManager.GetString("DS_TemperatureAndHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Measurement settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_Title {
            get {
                return ResourceManager.GetString("DS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting up for voltage adjustment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_VelocityVoltageSetting {
            get {
                return ResourceManager.GetString("DS_VelocityVoltageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PC connection settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DS_ZigbeeSetting {
            get {
                return ResourceManager.GetString("DS_ZigbeeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit measured data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditMeasuredData {
            get {
                return ResourceManager.GetString("EditMeasuredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specific enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Enthalpy {
            get {
                return ResourceManager.GetString("Enthalpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Globe temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GlobeTemperature {
            get {
                return ResourceManager.GetString("GlobeTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Globe temperature voltage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GlobeTemperatureVoltage {
            get {
                return ResourceManager.GetString("GlobeTemperatureVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hour に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Illuminance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Illuminance {
            get {
                return ResourceManager.GetString("Illuminance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_Copy {
            get {
                return ResourceManager.GetString("LD_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_Delete {
            get {
                return ResourceManager.GetString("LD_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_DeleteAlert {
            get {
                return ResourceManager.GetString("LD_DeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The maximum number of items displayed has been exceeded. Please copy them on the clipboard. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_Exceed {
            get {
                return ResourceManager.GetString("LD_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_Format {
            get {
                return ResourceManager.GetString("LD_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Formatting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_Formatting {
            get {
                return ResourceManager.GetString("LD_Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Measured data files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_List {
            get {
                return ResourceManager.GetString("LD_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No data stored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_NoData {
            get {
                return ResourceManager.GetString("LD_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logging data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LD_Title {
            get {
                return ResourceManager.GetString("LD_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute humidity and Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_AhmdAndDens {
            get {
                return ResourceManager.GetString("MA_AhmdAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute humidity and Enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_AhmdAndEnth {
            get {
                return ResourceManager.GetString("MA_AhmdAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute humdity and Wet-bulb temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_AhmdAndWbt {
            get {
                return ResourceManager.GetString("MA_AhmdAndWbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Absolute humdity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndAhmd {
            get {
                return ResourceManager.GetString("MA_DbtAndAhmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndDens {
            get {
                return ResourceManager.GetString("MA_DbtAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndEnth {
            get {
                return ResourceManager.GetString("MA_DbtAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Relative humidity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndRhmd {
            get {
                return ResourceManager.GetString("MA_DbtAndRhmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dry-bulb temperature and Wet-bulb temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_DbtAndWbt {
            get {
                return ResourceManager.GetString("MA_DbtAndWbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity and Absolute humdity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_RhmdAndAhmd {
            get {
                return ResourceManager.GetString("MA_RhmdAndAhmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity and Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_RhmdAndDens {
            get {
                return ResourceManager.GetString("MA_RhmdAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity and Enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_RhmdAndEnth {
            get {
                return ResourceManager.GetString("MA_RhmdAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity and Wet-bulb temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_RhmdAndWbt {
            get {
                return ResourceManager.GetString("MA_RhmdAndWbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summer-indoor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_SummerIndoor {
            get {
                return ResourceManager.GetString("MA_SummerIndoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summer-outdoor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_SummerOutdoor {
            get {
                return ResourceManager.GetString("MA_SummerOutdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wet-bulb temperature and Density に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_WbtAndDens {
            get {
                return ResourceManager.GetString("MA_WbtAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wet-bulb temperature and Enthalpy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_WbtAndEnth {
            get {
                return ResourceManager.GetString("MA_WbtAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Winter-indoor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_WinterIndoor {
            get {
                return ResourceManager.GetString("MA_WinterIndoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Winter-outdoor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MA_WinterOutdoor {
            get {
                return ResourceManager.GetString("MA_WinterOutdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mean radiant temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MeanRadiantTemperature {
            get {
                return ResourceManager.GetString("MeanRadiantTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metabolic rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetabolicUnit {
            get {
                return ResourceManager.GetString("MetabolicUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moist air calculator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS_Title {
            get {
                return ResourceManager.GetString("MS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative air velocity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RelativeAirVelocity {
            get {
                return ResourceManager.GetString("RelativeAirVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative humidity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RelativeHumidity {
            get {
                return ResourceManager.GetString("RelativeHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relayed data viewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RV_Title {
            get {
                return ResourceManager.GetString("RV_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enable Bluetooth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Bluetooth {
            get {
                return ResourceManager.GetString("SC_Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting to M-Logger... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Connecting {
            get {
                return ResourceManager.GetString("SC_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Empty {
            get {
                return ResourceManager.GetString("SC_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M-Logger not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Notfound {
            get {
                return ResourceManager.GetString("SC_Notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scanning MLogger... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Scannning {
            get {
                return ResourceManager.GetString("SC_Scannning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ML scanner に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SC_Title {
            get {
                return ResourceManager.GetString("SC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thermal comfort calculator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TC_Title {
            get {
                return ResourceManager.GetString("TC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Velocity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Velocity voltage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VelocityVoltage {
            get {
                return ResourceManager.GetString("VelocityVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enclose the velocity probe so that there is no wind, wait 30 seconds for it to stabilize, and then adjust the voltage to a range of 1.45 ± 0.5 V. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VT_VelocityAdjustMessage {
            get {
                return ResourceManager.GetString("VT_VelocityAdjustMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wet-bulb temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WetbulbTemperature {
            get {
                return ResourceManager.GetString("WetbulbTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
