//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLS_Mobile.Resources.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MLSResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MLSResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLS_Mobile.Resources.i18n.MLSResource", typeof(MLSResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this software.
        /// </summary>
        internal static string AboutThisSoftware {
            get {
                return ResourceManager.GetString("AboutThisSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute humidity.
        /// </summary>
        internal static string AbsoluteHumidity {
            get {
                return ResourceManager.GetString("AbsoluteHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmospheric pressure.
        /// </summary>
        internal static string AtmosphericPressure {
            get {
                return ResourceManager.GetString("AtmosphericPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing coordinator.
        /// </summary>
        internal static string CC_Title {
            get {
                return ResourceManager.GetString("CC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string CF_Back {
            get {
                return ResourceManager.GetString("CF_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV =.
        /// </summary>
        internal static string CF_CorrectionValue {
            get {
                return ResourceManager.GetString("CF_CorrectionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard the entries ?.
        /// </summary>
        internal static string CF_Discard {
            get {
                return ResourceManager.GetString("CF_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction factor {0} of {1} is invalid..
        /// </summary>
        internal static string CF_Invalid {
            get {
                return ResourceManager.GetString("CF_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage at 0m/s velocity is invalid..
        /// </summary>
        internal static string CF_InvalidVelocity1 {
            get {
                return ResourceManager.GetString("CF_InvalidVelocity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage at 0m/s velocity should be positive..
        /// </summary>
        internal static string CF_InvalidVelocity2 {
            get {
                return ResourceManager.GetString("CF_InvalidVelocity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading correction factors....
        /// </summary>
        internal static string CF_Loading {
            get {
                return ResourceManager.GetString("CF_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load correction factors..
        /// </summary>
        internal static string CF_LoadingError {
            get {
                return ResourceManager.GetString("CF_LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * meas. + .
        /// </summary>
        internal static string CF_Measurement {
            get {
                return ResourceManager.GetString("CF_Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string CF_Set {
            get {
                return ResourceManager.GetString("CF_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction factor setting.
        /// </summary>
        internal static string CF_Title {
            get {
                return ResourceManager.GetString("CF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No wind voltage: .
        /// </summary>
        internal static string CF_VelocityVoltage {
            get {
                return ResourceManager.GetString("CF_VelocityVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing unit.
        /// </summary>
        internal static string ClothingUnit {
            get {
                return ResourceManager.GetString("ClothingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to MLogger.
        /// </summary>
        internal static string ConnectMLogger {
            get {
                return ResourceManager.GetString("ConnectMLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density.
        /// </summary>
        internal static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to start logging..
        /// </summary>
        internal static string DR_FailStarting {
            get {
                return ResourceManager.GetString("DR_FailStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to stop logging..
        /// </summary>
        internal static string DR_FailStopping {
            get {
                return ResourceManager.GetString("DR_FailStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to finish the measurement?.
        /// </summary>
        internal static string DR_FinishAlert {
            get {
                return ResourceManager.GetString("DR_FinishAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish measurement.
        /// </summary>
        internal static string DR_FinishMeasurement {
            get {
                return ResourceManager.GetString("DR_FinishMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start logging....
        /// </summary>
        internal static string DR_StartLogging {
            get {
                return ResourceManager.GetString("DR_StartLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop logging....
        /// </summary>
        internal static string DR_StopLogging {
            get {
                return ResourceManager.GetString("DR_StopLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date receiver.
        /// </summary>
        internal static string DR_Title {
            get {
                return ResourceManager.GetString("DR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry-bulb temp..
        /// </summary>
        internal static string DrybulbTemperature {
            get {
                return ResourceManager.GetString("DrybulbTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set correction factor.
        /// </summary>
        internal static string DS_CFactor {
            get {
                return ResourceManager.GetString("DS_CFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicate with MLogger.
        /// </summary>
        internal static string DS_Communicate {
            get {
                return ResourceManager.GetString("DS_Communicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device information.
        /// </summary>
        internal static string DS_Info {
            get {
                return ResourceManager.GetString("DS_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string DS_LoadSetting {
            get {
                return ResourceManager.GetString("DS_LoadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string DS_SaveSetting {
            get {
                return ResourceManager.GetString("DS_SaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start logging to SD card.
        /// </summary>
        internal static string DS_SDLogging {
            get {
                return ResourceManager.GetString("DS_SDLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC address.
        /// </summary>
        internal static string DS_SpecMACAdd {
            get {
                return ResourceManager.GetString("DS_SpecMACAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DS_SpecName {
            get {
                return ResourceManager.GetString("DS_SpecName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLogger version.
        /// </summary>
        internal static string DS_SpecVersion {
            get {
                return ResourceManager.GetString("DS_SpecVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XBee address.
        /// </summary>
        internal static string DS_SpecXBAdd {
            get {
                return ResourceManager.GetString("DS_SpecXBAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string DS_Start {
            get {
                return ResourceManager.GetString("DS_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting date and time.
        /// </summary>
        internal static string DS_StartDTime {
            get {
                return ResourceManager.GetString("DS_StartDTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target and time interval.
        /// </summary>
        internal static string DS_TargetAndTimeInterval {
            get {
                return ResourceManager.GetString("DS_TargetAndTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature and relative humidity.
        /// </summary>
        internal static string DS_TemperatureAndHumidity {
            get {
                return ResourceManager.GetString("DS_TemperatureAndHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement settings.
        /// </summary>
        internal static string DS_Title {
            get {
                return ResourceManager.GetString("DS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit measured data.
        /// </summary>
        internal static string EditMeasuredData {
            get {
                return ResourceManager.GetString("EditMeasuredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific enthalpy.
        /// </summary>
        internal static string Enthalpy {
            get {
                return ResourceManager.GetString("Enthalpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globe temperature.
        /// </summary>
        internal static string GlobeTemperature {
            get {
                return ResourceManager.GetString("GlobeTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globe temperature voltage.
        /// </summary>
        internal static string GlobeTemperatureVoltage {
            get {
                return ResourceManager.GetString("GlobeTemperatureVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illuminance.
        /// </summary>
        internal static string Illuminance {
            get {
                return ResourceManager.GetString("Illuminance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string LD_Copy {
            get {
                return ResourceManager.GetString("LD_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string LD_Delete {
            get {
                return ResourceManager.GetString("LD_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the file?.
        /// </summary>
        internal static string LD_DeleteAlert {
            get {
                return ResourceManager.GetString("LD_DeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string LD_Format {
            get {
                return ResourceManager.GetString("LD_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        internal static string LD_Formatting {
            get {
                return ResourceManager.GetString("LD_Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured data files.
        /// </summary>
        internal static string LD_List {
            get {
                return ResourceManager.GetString("LD_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data stored..
        /// </summary>
        internal static string LD_NoData {
            get {
                return ResourceManager.GetString("LD_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging data.
        /// </summary>
        internal static string LD_Title {
            get {
                return ResourceManager.GetString("LD_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute humidity and Density.
        /// </summary>
        internal static string MA_AhmdAndDens {
            get {
                return ResourceManager.GetString("MA_AhmdAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute humidity and Enthalpy.
        /// </summary>
        internal static string MA_AhmdAndEnth {
            get {
                return ResourceManager.GetString("MA_AhmdAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute humdity and Wet-bulb temperature.
        /// </summary>
        internal static string MA_AhmdAndWbt {
            get {
                return ResourceManager.GetString("MA_AhmdAndWbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry-bulb temperature and Absolute humdity.
        /// </summary>
        internal static string MA_DbtAndAhmd {
            get {
                return ResourceManager.GetString("MA_DbtAndAhmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry-bulb temperature and Density.
        /// </summary>
        internal static string MA_DbtAndDens {
            get {
                return ResourceManager.GetString("MA_DbtAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry-bulb temperature and Enthalpy.
        /// </summary>
        internal static string MA_DbtAndEnth {
            get {
                return ResourceManager.GetString("MA_DbtAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry-bulb temperature and Relative humidity.
        /// </summary>
        internal static string MA_DbtAndRhmd {
            get {
                return ResourceManager.GetString("MA_DbtAndRhmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry-bulb temperature and Wet-bulb temperature.
        /// </summary>
        internal static string MA_DbtAndWbt {
            get {
                return ResourceManager.GetString("MA_DbtAndWbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative humidity and Absolute humdity.
        /// </summary>
        internal static string MA_RhmdAndAhmd {
            get {
                return ResourceManager.GetString("MA_RhmdAndAhmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative humidity and Density.
        /// </summary>
        internal static string MA_RhmdAndDens {
            get {
                return ResourceManager.GetString("MA_RhmdAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative humidity and Enthalpy.
        /// </summary>
        internal static string MA_RhmdAndEnth {
            get {
                return ResourceManager.GetString("MA_RhmdAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative humidity and Wet-bulb temperature.
        /// </summary>
        internal static string MA_RhmdAndWbt {
            get {
                return ResourceManager.GetString("MA_RhmdAndWbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer-indoor.
        /// </summary>
        internal static string MA_SummerIndoor {
            get {
                return ResourceManager.GetString("MA_SummerIndoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer-outdoor.
        /// </summary>
        internal static string MA_SummerOutdoor {
            get {
                return ResourceManager.GetString("MA_SummerOutdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wet-bulb temperature and Density.
        /// </summary>
        internal static string MA_WbtAndDens {
            get {
                return ResourceManager.GetString("MA_WbtAndDens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wet-bulb temperature and Enthalpy.
        /// </summary>
        internal static string MA_WbtAndEnth {
            get {
                return ResourceManager.GetString("MA_WbtAndEnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter-indoor.
        /// </summary>
        internal static string MA_WinterIndoor {
            get {
                return ResourceManager.GetString("MA_WinterIndoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter-outdoor.
        /// </summary>
        internal static string MA_WinterOutdoor {
            get {
                return ResourceManager.GetString("MA_WinterOutdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean radiant temperature.
        /// </summary>
        internal static string MeanRadiantTemperature {
            get {
                return ResourceManager.GetString("MeanRadiantTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metabolic rate.
        /// </summary>
        internal static string MetabolicUnit {
            get {
                return ResourceManager.GetString("MetabolicUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moist air calculator.
        /// </summary>
        internal static string MS_Title {
            get {
                return ResourceManager.GetString("MS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative air velocity.
        /// </summary>
        internal static string RelativeAirVelocity {
            get {
                return ResourceManager.GetString("RelativeAirVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative humidity.
        /// </summary>
        internal static string RelativeHumidity {
            get {
                return ResourceManager.GetString("RelativeHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable Bluetooth.
        /// </summary>
        internal static string SC_Bluetooth {
            get {
                return ResourceManager.GetString("SC_Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting MLogger....
        /// </summary>
        internal static string SC_Connecting {
            get {
                return ResourceManager.GetString("SC_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string SC_Empty {
            get {
                return ResourceManager.GetString("SC_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLogger not found.
        /// </summary>
        internal static string SC_Notfound {
            get {
                return ResourceManager.GetString("SC_Notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning MLogger....
        /// </summary>
        internal static string SC_Scannning {
            get {
                return ResourceManager.GetString("SC_Scannning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLogger scanner.
        /// </summary>
        internal static string SC_Title {
            get {
                return ResourceManager.GetString("SC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal comfort calculator.
        /// </summary>
        internal static string TC_Title {
            get {
                return ResourceManager.GetString("TC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity voltage.
        /// </summary>
        internal static string VelocityVoltage {
            get {
                return ResourceManager.GetString("VelocityVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wet-bulb temperature.
        /// </summary>
        internal static string WetbulbTemperature {
            get {
                return ResourceManager.GetString("WetbulbTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
