//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLS_Mobile.Resources.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TCResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TCResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLS_Mobile.Resources.i18n.TCResource", typeof(TCResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft, combat.
        /// </summary>
        internal static string Act_Aircraft_Combat {
            get {
                return ResourceManager.GetString("Act_Aircraft_Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft, instrument landing.
        /// </summary>
        internal static string Act_Aircraft_InstrumentLanding {
            get {
                return ResourceManager.GetString("Act_Aircraft_InstrumentLanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft, routine.
        /// </summary>
        internal static string Act_Aircraft_Routine {
            get {
                return ResourceManager.GetString("Act_Aircraft_Routine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automobile.
        /// </summary>
        internal static string Act_Automobile {
            get {
                return ResourceManager.GetString("Act_Automobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basketball.
        /// </summary>
        internal static string Act_Basketball {
            get {
                return ResourceManager.GetString("Act_Basketball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calisthenics/exercise.
        /// </summary>
        internal static string Act_Calisthenics {
            get {
                return ResourceManager.GetString("Act_Calisthenics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking.
        /// </summary>
        internal static string Act_Cooking {
            get {
                return ResourceManager.GetString("Act_Cooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancing, social.
        /// </summary>
        internal static string Act_Dancing {
            get {
                return ResourceManager.GetString("Act_Dancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filing, seated.
        /// </summary>
        internal static string Act_FilingSeated {
            get {
                return ResourceManager.GetString("Act_FilingSeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filing, standing.
        /// </summary>
        internal static string Act_FilingStanding {
            get {
                return ResourceManager.GetString("Act_FilingStanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling 50 kg (100 lb) bags.
        /// </summary>
        internal static string Act_HandlingBags {
            get {
                return ResourceManager.GetString("Act_HandlingBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        internal static string Act_Heavy {
            get {
                return ResourceManager.GetString("Act_Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seated, heavy limb movement.
        /// </summary>
        internal static string Act_HeavyLimbMovement {
            get {
                return ResourceManager.GetString("Act_HeavyLimbMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy vehicle.
        /// </summary>
        internal static string Act_HeavyVehicle {
            get {
                return ResourceManager.GetString("Act_HeavyVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House cleaning.
        /// </summary>
        internal static string Act_HouseCleaning {
            get {
                return ResourceManager.GetString("Act_HouseCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifting/packing.
        /// </summary>
        internal static string Act_Lifting_Packing {
            get {
                return ResourceManager.GetString("Act_Lifting_Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light (electrical industry).
        /// </summary>
        internal static string Act_Light {
            get {
                return ResourceManager.GetString("Act_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seated, reading, or writing.
        /// </summary>
        internal static string Act_Of_Seated {
            get {
                return ResourceManager.GetString("Act_Of_Seated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick and shovel work.
        /// </summary>
        internal static string Act_PickAndShovelWork {
            get {
                return ResourceManager.GetString("Act_PickAndShovelWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reclining.
        /// </summary>
        internal static string Act_Reclining {
            get {
                return ResourceManager.GetString("Act_Reclining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sawing (table saw).
        /// </summary>
        internal static string Act_Sawing {
            get {
                return ResourceManager.GetString("Act_Sawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seated, quiet.
        /// </summary>
        internal static string Act_Seated_quiet {
            get {
                return ResourceManager.GetString("Act_Seated_quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeping.
        /// </summary>
        internal static string Act_Sleeping {
            get {
                return ResourceManager.GetString("Act_Sleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing, relaxed.
        /// </summary>
        internal static string Act_Standing_relaxed {
            get {
                return ResourceManager.GetString("Act_Standing_relaxed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis, single.
        /// </summary>
        internal static string Act_Tennis {
            get {
                return ResourceManager.GetString("Act_Tennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving/Flying.
        /// </summary>
        internal static string Act_Title_Driving {
            get {
                return ResourceManager.GetString("Act_Title_Driving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Leisure Activities.
        /// </summary>
        internal static string Act_Title_LeisureActivities {
            get {
                return ResourceManager.GetString("Act_Title_LeisureActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine work.
        /// </summary>
        internal static string Act_Title_MachineWork {
            get {
                return ResourceManager.GetString("Act_Title_MachineWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Occupational Activities.
        /// </summary>
        internal static string Act_Title_OccupationalActivities {
            get {
                return ResourceManager.GetString("Act_Title_OccupationalActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Activities.
        /// </summary>
        internal static string Act_Title_OfficeActivities {
            get {
                return ResourceManager.GetString("Act_Title_OfficeActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resting.
        /// </summary>
        internal static string Act_Title_Resting {
            get {
                return ResourceManager.GetString("Act_Title_Resting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking.
        /// </summary>
        internal static string Act_Title_Walking {
            get {
                return ResourceManager.GetString("Act_Title_Walking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing.
        /// </summary>
        internal static string Act_Typing {
            get {
                return ResourceManager.GetString("Act_Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.9 m/s, 3.2 km/h, 2.0 mph.
        /// </summary>
        internal static string Act_Walking_09 {
            get {
                return ResourceManager.GetString("Act_Walking_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2 m/s, 4.3 km/h, 2.7 mph.
        /// </summary>
        internal static string Act_Walking_12 {
            get {
                return ResourceManager.GetString("Act_Walking_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.8 m/s, 6.8 km/h, 4.2 mph.
        /// </summary>
        internal static string Act_Walking_18 {
            get {
                return ResourceManager.GetString("Act_Walking_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking about.
        /// </summary>
        internal static string Act_WalkingAbout {
            get {
                return ResourceManager.GetString("Act_WalkingAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrestling, competitive.
        /// </summary>
        internal static string Act_Wrestling {
            get {
                return ResourceManager.GetString("Act_Wrestling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basketball.
        /// </summary>
        internal static string Basketball {
            get {
                return ResourceManager.GetString("Basketball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ankle-length athletic socks.
        /// </summary>
        internal static string Clo_AnkleLengthAthleticSocks {
            get {
                return ResourceManager.GetString("Clo_AnkleLengthAthleticSocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boots.
        /// </summary>
        internal static string Clo_Boots {
            get {
                return ResourceManager.GetString("Clo_Boots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bra.
        /// </summary>
        internal static string Clo_Bra {
            get {
                return ResourceManager.GetString("Clo_Bra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calf-length socks.
        /// </summary>
        internal static string Clo_CalfLengthSocks {
            get {
                return ResourceManager.GetString("Clo_CalfLengthSocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coveralls.
        /// </summary>
        internal static string Clo_Coveralls {
            get {
                return ResourceManager.GetString("Clo_Coveralls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-breasted (thick).
        /// </summary>
        internal static string Clo_DoubleBreastedThick {
            get {
                return ResourceManager.GetString("Clo_DoubleBreastedThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-breasted (thin).
        /// </summary>
        internal static string Clo_DoubleBreastedThin {
            get {
                return ResourceManager.GetString("Clo_DoubleBreastedThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full slip.
        /// </summary>
        internal static string Clo_FullSlip {
            get {
                return ResourceManager.GetString("Clo_FullSlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-slip.
        /// </summary>
        internal static string Clo_HalfSlip {
            get {
                return ResourceManager.GetString("Clo_HalfSlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knee socks (thick).
        /// </summary>
        internal static string Clo_KneeSocks_Thick {
            get {
                return ResourceManager.GetString("Clo_KneeSocks_Thick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-sleeve dress shirt.
        /// </summary>
        internal static string Clo_LongSleeveDressShirt {
            get {
                return ResourceManager.GetString("Clo_LongSleeveDressShirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-sleeve flannel shirt.
        /// </summary>
        internal static string Clo_LongSleeveFlannel {
            get {
                return ResourceManager.GetString("Clo_LongSleeveFlannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-sleeve long gown (thick).
        /// </summary>
        internal static string Clo_LongSleeveLongGownThick {
            get {
                return ResourceManager.GetString("Clo_LongSleeveLongGownThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-sleeve long wrap robe (thick).
        /// </summary>
        internal static string Clo_LongSleeveLongWrapRobeThick {
            get {
                return ResourceManager.GetString("Clo_LongSleeveLongWrapRobeThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-sleeve pajamas (thick).
        /// </summary>
        internal static string Clo_LongSleevePajamasThick {
            get {
                return ResourceManager.GetString("Clo_LongSleevePajamasThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-sleeve shirtdress (thick).
        /// </summary>
        internal static string Clo_LongSleeveShirtDressThick {
            get {
                return ResourceManager.GetString("Clo_LongSleeveShirtDressThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-sleeve shirtdress (thin).
        /// </summary>
        internal static string Clo_LongSleeveShirtDressThin {
            get {
                return ResourceManager.GetString("Clo_LongSleeveShirtDressThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-sleeve short wrap robe (thick).
        /// </summary>
        internal static string Clo_LongSleeveShortWrapRobeThick {
            get {
                return ResourceManager.GetString("Clo_LongSleeveShortWrapRobeThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-sleeve sweatshirt.
        /// </summary>
        internal static string Clo_LongSleeveSweatShirt {
            get {
                return ResourceManager.GetString("Clo_LongSleeveSweatShirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-sleeve (thick).
        /// </summary>
        internal static string Clo_LongSleeveThick {
            get {
                return ResourceManager.GetString("Clo_LongSleeveThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-sleeve (thin).
        /// </summary>
        internal static string Clo_LongSleeveThin {
            get {
                return ResourceManager.GetString("Clo_LongSleeveThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long underwear bottoms.
        /// </summary>
        internal static string Clo_LongUnderwearBottoms {
            get {
                return ResourceManager.GetString("Clo_LongUnderwearBottoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long underwear top.
        /// </summary>
        internal static string Clo_LongUnderwearTop {
            get {
                return ResourceManager.GetString("Clo_LongUnderwearTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men&apos;s briefs.
        /// </summary>
        internal static string Clo_MensBriefs {
            get {
                return ResourceManager.GetString("Clo_MensBriefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overalls.
        /// </summary>
        internal static string Clo_Overalls {
            get {
                return ResourceManager.GetString("Clo_Overalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panties.
        /// </summary>
        internal static string Clo_Panties {
            get {
                return ResourceManager.GetString("Clo_Panties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pantyhose/stockings.
        /// </summary>
        internal static string Clo_Pantyhose_Stockings {
            get {
                return ResourceManager.GetString("Clo_Pantyhose_Stockings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandals/thongs.
        /// </summary>
        internal static string Clo_Sandals_Thongs {
            get {
                return ResourceManager.GetString("Clo_Sandals_Thongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        internal static string Clo_Shoes {
            get {
                return ResourceManager.GetString("Clo_Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short shorts.
        /// </summary>
        internal static string Clo_ShortShorts {
            get {
                return ResourceManager.GetString("Clo_ShortShorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-sleeve dress shirt.
        /// </summary>
        internal static string Clo_ShortSleeveDressShirt {
            get {
                return ResourceManager.GetString("Clo_ShortSleeveDressShirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-sleeve hospital gown.
        /// </summary>
        internal static string Clo_ShortSleeveHospitalGown {
            get {
                return ResourceManager.GetString("Clo_ShortSleeveHospitalGown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-sleeve knit sport shirt.
        /// </summary>
        internal static string Clo_ShortSleeveKnit {
            get {
                return ResourceManager.GetString("Clo_ShortSleeveKnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-sleeve pajamas (thin).
        /// </summary>
        internal static string Clo_ShortSleevePajamasThin {
            get {
                return ResourceManager.GetString("Clo_ShortSleevePajamasThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-sleeve shirtdress (thin).
        /// </summary>
        internal static string Clo_ShortSleeveShirtDressThin {
            get {
                return ResourceManager.GetString("Clo_ShortSleeveShirtDressThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-sleeve short robe (thin).
        /// </summary>
        internal static string Clo_ShortSleeveShortRobeThin {
            get {
                return ResourceManager.GetString("Clo_ShortSleeveShortRobeThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-breasted (thick).
        /// </summary>
        internal static string Clo_SingleBreastedThick {
            get {
                return ResourceManager.GetString("Clo_SingleBreastedThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-breasted (thin).
        /// </summary>
        internal static string Clo_SingleBreastedThin {
            get {
                return ResourceManager.GetString("Clo_SingleBreastedThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skirt (thick).
        /// </summary>
        internal static string Clo_SkirtThick {
            get {
                return ResourceManager.GetString("Clo_SkirtThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skirt (thin).
        /// </summary>
        internal static string Clo_SkirtThin {
            get {
                return ResourceManager.GetString("Clo_SkirtThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeveless/scoop-neck blouse.
        /// </summary>
        internal static string Clo_Sleeveless {
            get {
                return ResourceManager.GetString("Clo_Sleeveless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeveless long gown (thin).
        /// </summary>
        internal static string Clo_SleevelessLongGownThin {
            get {
                return ResourceManager.GetString("Clo_SleevelessLongGownThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeveless short gown (thin).
        /// </summary>
        internal static string Clo_SleevelessShortGownThin {
            get {
                return ResourceManager.GetString("Clo_SleevelessShortGownThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeveless vest (thick).
        /// </summary>
        internal static string Clo_SleevelessSweatVestThick {
            get {
                return ResourceManager.GetString("Clo_SleevelessSweatVestThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeveless vest (thin).
        /// </summary>
        internal static string Clo_SleevelessSweatVestThin {
            get {
                return ResourceManager.GetString("Clo_SleevelessSweatVestThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeveless, scoop neck (thick), i.e.,jumper.
        /// </summary>
        internal static string Clo_SleevelessThick {
            get {
                return ResourceManager.GetString("Clo_SleevelessThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeveless, scoop neck (thin).
        /// </summary>
        internal static string Clo_SleevelessThin {
            get {
                return ResourceManager.GetString("Clo_SleevelessThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeveless vest (thick).
        /// </summary>
        internal static string Clo_SleevelessVestThick {
            get {
                return ResourceManager.GetString("Clo_SleevelessVestThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeveless vest (thin).
        /// </summary>
        internal static string Clo_SleevelessVestThin {
            get {
                return ResourceManager.GetString("Clo_SleevelessVestThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slippers (quilted, pile lined).
        /// </summary>
        internal static string Clo_Slippers {
            get {
                return ResourceManager.GetString("Clo_Slippers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight trousers (thick).
        /// </summary>
        internal static string Clo_StraightTrousersThick {
            get {
                return ResourceManager.GetString("Clo_StraightTrousersThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight trousers (thin).
        /// </summary>
        internal static string Clo_StraightTrousersThin {
            get {
                return ResourceManager.GetString("Clo_StraightTrousersThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweatpants.
        /// </summary>
        internal static string Clo_Sweatpants {
            get {
                return ResourceManager.GetString("Clo_Sweatpants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dress and Skirts.
        /// </summary>
        internal static string Clo_Title_DressAndSkirts {
            get {
                return ResourceManager.GetString("Clo_Title_DressAndSkirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footwear.
        /// </summary>
        internal static string Clo_Title_Footwear {
            get {
                return ResourceManager.GetString("Clo_Title_Footwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirts and Blouses.
        /// </summary>
        internal static string Clo_Title_ShirtsAndBlouses {
            get {
                return ResourceManager.GetString("Clo_Title_ShirtsAndBlouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleepwear and Robes.
        /// </summary>
        internal static string Clo_Title_SleepwearAndRobes {
            get {
                return ResourceManager.GetString("Clo_Title_SleepwearAndRobes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suit Jackets and Vests.
        /// </summary>
        internal static string Clo_Title_SuitJacketsAndVests {
            get {
                return ResourceManager.GetString("Clo_Title_SuitJacketsAndVests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweaters.
        /// </summary>
        internal static string Clo_Title_Sweaters {
            get {
                return ResourceManager.GetString("Clo_Title_Sweaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trousers and Coveralls.
        /// </summary>
        internal static string Clo_Title_TrousersAndCoveralls {
            get {
                return ResourceManager.GetString("Clo_Title_TrousersAndCoveralls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwear.
        /// </summary>
        internal static string Clo_Title_Underwear {
            get {
                return ResourceManager.GetString("Clo_Title_Underwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-shirt.
        /// </summary>
        internal static string Clo_TShirt {
            get {
                return ResourceManager.GetString("Clo_TShirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking shorts.
        /// </summary>
        internal static string Clo_WalkingShorts {
            get {
                return ResourceManager.GetString("Clo_WalkingShorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking.
        /// </summary>
        internal static string Cooling {
            get {
                return ResourceManager.GetString("Cooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancing, social.
        /// </summary>
        internal static string Dancing {
            get {
                return ResourceManager.GetString("Dancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving/Flying: Aircraft, routine.
        /// </summary>
        internal static string Driving_Aircraft1 {
            get {
                return ResourceManager.GetString("Driving_Aircraft1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving/Flying: Aircraft, instrument landing.
        /// </summary>
        internal static string Driving_Aircraft2 {
            get {
                return ResourceManager.GetString("Driving_Aircraft2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving/Flying: Aircraft, combat.
        /// </summary>
        internal static string Driving_Aircraft3 {
            get {
                return ResourceManager.GetString("Driving_Aircraft3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving/Flying: Automobile.
        /// </summary>
        internal static string Driving_Automobile {
            get {
                return ResourceManager.GetString("Driving_Automobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving/Flying: Heavy vehicle.
        /// </summary>
        internal static string Driving_Heavy {
            get {
                return ResourceManager.GetString("Driving_Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calisthenics/exercise.
        /// </summary>
        internal static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seated, heavy limb movement.
        /// </summary>
        internal static string HeavyLimbMovement {
            get {
                return ResourceManager.GetString("HeavyLimbMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House cleaning.
        /// </summary>
        internal static string HouseCleaning {
            get {
                return ResourceManager.GetString("HouseCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine work: Handling 50 kg (100 lb) bags.
        /// </summary>
        internal static string Mw_HandlingBags {
            get {
                return ResourceManager.GetString("Mw_HandlingBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine work: Heavy.
        /// </summary>
        internal static string Mw_Heavy {
            get {
                return ResourceManager.GetString("Mw_Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine work: Light (electrical industry).
        /// </summary>
        internal static string Mw_Light {
            get {
                return ResourceManager.GetString("Mw_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine work: Sawing (table saw).
        /// </summary>
        internal static string Mw_Sawing {
            get {
                return ResourceManager.GetString("Mw_Sawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine work: Pick and shovel work.
        /// </summary>
        internal static string Mw_ShovelWork {
            get {
                return ResourceManager.GetString("Mw_ShovelWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Activities: Filing, seated.
        /// </summary>
        internal static string Of_FilingSeated {
            get {
                return ResourceManager.GetString("Of_FilingSeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Activities: Filing, standing.
        /// </summary>
        internal static string Of_FilingStanding {
            get {
                return ResourceManager.GetString("Of_FilingStanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Activities: Lifting/packing.
        /// </summary>
        internal static string Of_Lifting {
            get {
                return ResourceManager.GetString("Of_Lifting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Activities: Seated, reading, or writing.
        /// </summary>
        internal static string Of_Seated {
            get {
                return ResourceManager.GetString("Of_Seated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Activities: Typing.
        /// </summary>
        internal static string Of_Typing {
            get {
                return ResourceManager.GetString("Of_Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Activities: Walking about.
        /// </summary>
        internal static string Of_Walking {
            get {
                return ResourceManager.GetString("Of_Walking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resting: Reclining.
        /// </summary>
        internal static string Rs_Reclining {
            get {
                return ResourceManager.GetString("Rs_Reclining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resting: Seated, quiet.
        /// </summary>
        internal static string Rs_Seated {
            get {
                return ResourceManager.GetString("Rs_Seated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resting: Sleeping.
        /// </summary>
        internal static string Rs_Sleeping {
            get {
                return ResourceManager.GetString("Rs_Sleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resting: Standing, relaxed.
        /// </summary>
        internal static string Rs_Standing {
            get {
                return ResourceManager.GetString("Rs_Standing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select activity.
        /// </summary>
        internal static string SelectActivity {
            get {
                return ResourceManager.GetString("SelectActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select clothes.
        /// </summary>
        internal static string SelectClothes {
            get {
                return ResourceManager.GetString("SelectClothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis, single.
        /// </summary>
        internal static string Tennis {
            get {
                return ResourceManager.GetString("Tennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking: 0.9 m/s, 3.2 km/h, 2.0 mph.
        /// </summary>
        internal static string Walking_09 {
            get {
                return ResourceManager.GetString("Walking_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking: 1.2 m/s, 4.3 km/h, 2.7 mph.
        /// </summary>
        internal static string Walking_12 {
            get {
                return ResourceManager.GetString("Walking_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking: 1.8 m/s, 6.8 km/h, 4.2 mph.
        /// </summary>
        internal static string Walking_18 {
            get {
                return ResourceManager.GetString("Walking_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrestling, competitive.
        /// </summary>
        internal static string Wrestling {
            get {
                return ResourceManager.GetString("Wrestling", resourceCulture);
            }
        }
    }
}
