//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLWebServer {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLWebServer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   /*! List.js v1.5.0 (http://listjs.com) by Jonny Str旦mberg (http://javve.com) */
        ///var List =
        ////******/ (function(modules) { // webpackBootstrap
        ////******/ 	// The module cache
        ////******/ 	var installedModules = {};
        ///
        ////******/ 	// The require function
        ////******/ 	function __webpack_require__(moduleId) {
        ///
        ////******/ 		// Check if module is in cache
        ////******/ 		if(installedModules[moduleId])
        ////******/ 			return installedModules[moduleId].exports;
        ///
        ////******/ 		// Create a new module (and put it into the cache)
        ////******/ 		var  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string list_js {
            get {
                return ResourceManager.GetString("list_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   body {
        ///  font-family: &quot;Open Sans&quot;, sans-serif;
        ///  line-height: 1.25;
        ///  background-color: #ffffff;
        ///}
        ///
        ///table {
        ///  border-collapse: collapse;
        ///  margin: 0 auto;
        ///  padding: 0;
        ///  width: 2100px;
        ///  table-layout: fixed;
        ///}
        ///
        ///table tr {
        ///  background-color: #e6f2f5;
        ///  padding: .35em;
        ///  border-bottom: 2px solid #fff;
        ///}
        ///table th,
        ///table td {
        ///  padding: 1em 10px 1em 1em;
        ///  border-right: 2px solid #fff;
        ///  text-align: center;
        ///}
        ///table th {
        ///  font-size: 1.0em;
        ///}
        ///table thead tr{
        ///  background-color: #16 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string style_css {
            get {
                return ResourceManager.GetString("style_css", resourceCulture);
            }
        }
    }
}
